export const actionsToStrings = {
  lstick: "Left Stick",
  rstick: "Right Stick",
  button: "Button",
  dpad: "DPad",
};

// ENUMS
export const LStick = "lstick";
export const RStick = "rstick";
export const Button = "button";
export const DPad = "dpad";
export const actionOrders = [LStick, RStick, Button, DPad];
export const actionSortOrder = {
  [LStick]: 0,
  [RStick]: 1,
  [Button]: 2,
  [DPad]: 3,
};
export const DPadMappings = {
  0: "⬆️",
  1: "↗️",
  2: "➡️",
  3: "↘️",
  4: "⬇️",
  5: "↙️",
  6: "⬅️",
  7: "↖️",
  8: "⏺️",
};
export const BtnY = "Y";
export const BtnB = "B";
export const BtnA = "A";
export const BtnX = "X";
export const BtnL = "L";
export const BtnR = "R";
export const BtnZL = "ZL";
export const BtnZR = "ZR";
export const BtnMinus = "MINUS";
export const BtnPlus = "PLUS";
export const BtnHome = "HOME";
export const BtnCapture = "CAPTURE";
export const BtnLClick = "LCLICK";
export const BtnRClick = "RCLICK";

// export const DPadCenter = 8;
// export const DPadUp = 0;
// export const DPadUpRight = 1;
// export const DPadRight = 2;
// export const DPadDownRight = 3;
// export const DPadDown = 4;
// export const DPadDownLeft = 5;
// export const DPadLeft = 6;
// export const DPadUpLeft = 7;

export const keyEventCodeToC = {
  KeyA: "A",
  KeyB: "B",
  KeyC: "C",
  KeyD: "D",
  KeyE: "E",
  KeyF: "F",
  KeyG: "G",
  KeyH: "H",
  KeyI: "I",
  KeyJ: "J",
  KeyK: "K",
  KeyL: "L",
  KeyM: "M",
  KeyN: "N",
  KeyO: "O",
  KeyP: "P",
  KeyQ: "Q",
  KeyR: "R",
  KeyS: "S",
  KeyT: "T",
  KeyU: "U",
  KeyV: "V",
  KeyW: "W",
  KeyX: "X",
  KeyY: "Y",
  KeyZ: "Z",
  Digit1: "1",
  Digit2: "2",
  Digit3: "3",
  Digit4: "4",
  Digit5: "5",
  Digit6: "6",
  Digit7: "7",
  Digit8: "8",
  Digit9: "9",
  Digit0: "0",
  Enter: "ENTER",
  Escape: "ESC",
  Backspace: "BACKSPACE",
  Tab: "TAB",
  Space: "SPACE",
  Minus: "MINUS",
  Equal: "EQUAL",
  BracketLeft: "LEFTBRACE",
  BracketRight: "RIGHTBRACE",
  Backslash: "BACKSLASH",
  Backquote: "HASHTILDE",
  Semicolon: "SEMICOLON",
  Quote: "APOSTROPHE",
  Backquote: "GRAVE",
  Comma: "COMMA",
  Period: "DOT",
  Slash: "SLASH",
  CapsLock: "CAPSLOCK",
  ControlLeft: "LEFTCTRL",
  ControlRight: "RIGHTCTRL",
  ShiftLeft: "LEFTSHIFT",
  ShiftRight: "RIGHTSHIFT",
  AltLeft: "LEFTALT",
  AltRight: "RIGHTALT",
  OSLeft: "LEFTMETA",
  MetaLeft: "LEFTMETA",
  OSRight: "RIGHTMETA",
  MetaRight: "RIGHTMETA",
  F1: "F1",
  F2: "F2",
  F3: "F3",
  F4: "F4",
  F5: "F5",
  F6: "F6",
  F7: "F7",
  F8: "F8",
  F9: "F9",
  F10: "F10",
  F11: "F11",
  F12: "F12",
  PrintScreen: "SYSRQ",
  ScrollLock: "SCROLLLOCK",
  Pause: "PAUSE",
  Insert: "INSERT",
  Home: "HOME",
  Delete: "DELETE",
  End: "END",
  PageDown: "PAGEDOWN",
  PageUp: "PAGEUP",
  ArrowRight: "RIGHT",
  ArrowLeft: "LEFT",
  ArrowDown: "DOWN",
  ArrowUp: "UP",
  NumLock: "NUMLOCK",
  Numpad1: "KP1",
  Numpad2: "KP2",
  Numpad3: "KP3",
  Numpad4: "KP4",
  Numpad5: "KP5",
  Numpad6: "KP6",
  Numpad7: "KP7",
  Numpad8: "KP8",
  Numpad9: "KP9",
  Numpad0: "KP0",
  NumpadDecimal: "KPDOT",
  NumpadEqual: "KPEQUAL",
  NumpadComma: "KPCOMMA",
  NumpadDivide: "KPSLASH",
  NumpadMultiply: "KPASTERISK",
  NumpadSubtract: "KPMINUS",
  NumpadAdd: "KPPLUS",
  NumpadEnter: "KPENTER",
  IntlBackslash: "102ND",
  // Compose: "COMPOSE",
  Power: "POWER",
  F13: "F13",
  F14: "F14",
  F15: "F15",
  F16: "F16",
  F17: "F17",
  F18: "F18",
  F19: "F19",
  F20: "F20",
  F21: "F21",
  F22: "F22",
  F23: "F23",
  F24: "F24",
  Open: "OPEN",
  Help: "HELP",
  Props: "PROPS",
  // Front: "FRONT",
  MediaStop: "STOP",
  Again: "AGAIN",
  Undo: "UNDO",
  Cut: "CUT",
  Copy: "COPY",
  Paste: "PASTE",
  Find: "FIND",
  AudioVolumeMute: "MUTE",
  VolumeMute: "MUTE",
  AudioVolumeUp: "VOLUMEUP",
  VolumeUp: "VOLUMEUP",
  AudioVolumeDown: "VOLUMEDOWN",
  VolumeDown: "VOLUMEDOWN",
  IntlRo: "RO",
  KanaMode: "KATAKANAHIRAGANA",
  IntlYen: "YEN",
  // Henkan: "HENKAN",
  // Muhenkan: "MUHENKAN",
  // Kpjpcomma: "KPJPCOMMA",
  Lang1: "HANGEUL",
  HangulMode: "HANGEUL",
  Lang2: "HANJA",
  Hanja: "HANJA",
  // Katakana: "KATAKANA",
  // Hiragana: "HIRAGANA",
  // Zenkakuhankaku: "ZENKAKUHANKAKU",
  // Kpleftparen: "KPLEFTPAREN",
  // Kprightparen: "KPRIGHTPAREN",
  MediaPlayPause: "MEDIA_PLAYPAUSE",
  // Media_stopcd: "MEDIA_STOPCD",
  // TODO: Finish setting up the rest of these below:
  // Media_previoussong: "MEDIA_PREVIOUSSONG",
  // Media_nextsong: "MEDIA_NEXTSONG",
  // Media_ejectcd: "MEDIA_EJECTCD",
  // Media_volumeup: "MEDIA_VOLUMEUP",
  // Media_volumedown: "MEDIA_VOLUMEDOWN",
  // Media_mute: "MEDIA_MUTE",
  // Media_www: "MEDIA_WWW",
  // Media_back: "MEDIA_BACK",
  // Media_forward: "MEDIA_FORWARD",
  // MediaStop: "MEDIA_STOP",
  // Media_find: "MEDIA_FIND",
  // Media_scrollup: "MEDIA_SCROLLUP",
  // Media_scrolldown: "MEDIA_SCROLLDOWN",
  // Media_edit: "MEDIA_EDIT",
  // Media_sleep: "MEDIA_SLEEP",
  // Media_coffee: "MEDIA_COFFEE",
  // Media_refresh: "MEDIA_REFRESH",
  // Media_calc: "MEDIA_CALC",
};
